---
# This playbook is configured to use TLS over TCP exclusively.

- name: install apt packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  sudo: True
  with_items:
    - rsyslog-gnutls
  notify: reload rsyslogd

- name: copy TLS certificate bundle
  copy: src=papertrail-bundle.pem dest=/etc/ mode=0644 owner=syslog
  notify: reload rsyslogd

- name: copy papertrail config file
  template: src=90-papertrail.conf.j2 dest=/etc/rsyslog.d/90-papertrail.conf
  notify: reload rsyslogd

- name: ensure rsyslogd is running
  service: name=rsyslog state=started
