---
- name: install apt packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  sudo: True
  with_items:
    - libpq-dev
    - postgresql
    - python-psycopg2

- name: copy configuration file
  copy: >
    src=postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf
    owner=postgres group=postgres mode=0644
  sudo: True
  notify: restart postgres

- name: copy client authentication configuration file
  copy: >
    src=pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
    owner=postgres group=postgres mode=0640
  sudo: True
  notify: restart postgres

- name: create a user
  postgresql_user:
    name: "{{ postgres_username }}"
    password: "{{ postgres_password }}"
  sudo: True
  sudo_user: postgres

- name: create the database
  postgresql_db:
    name: "{{ postgres_db_name }}"
    owner: "{{ postgres_username }}"
    encoding: UTF-8
    lc_ctype: "{{ postgres_locale }}"
    lc_collate: "{{ postgres_locale }}"
    template: template0
  sudo: True
  sudo_user: postgres
